/**
 * The migration journal — the index that says which snapshot belongs to which
 * migration file, and in what order they apply. Same shape drizzle-kit uses,
 * so a history generated by either tool is readable by the other.
 */
export interface JournalEntry {
	readonly idx: number;
	readonly version: string;
	readonly when: number;
	readonly tag: string;
	readonly breakpoints: boolean;
}

export interface Journal {
	readonly version: string;
	readonly dialect: 'sqlite';
	readonly entries: readonly JournalEntry[];
}

export const emptyJournal = (): Journal => ({ version: '7', dialect: 'sqlite', entries: [] });

export const nextIndex = (journal: Journal): number =>
	journal.entries.reduce((max, entry) => Math.max(max, entry.idx + 1), 0);

/** `0003_lively_moon` — the wrangler-compatible file naming. */
export const migrationTag = (index: number, name: string): string =>
	`${String(index).padStart(4, '0')}_${name}`;

export const appendEntry = (journal: Journal, tag: string, when: number): Journal => ({
	...journal,
	entries: [
		...journal.entries,
		{ idx: nextIndex(journal), version: '7', when, tag, breakpoints: true },
	],
});

/** Which journal entries have not been recorded in the database yet. */
export const pendingMigrations = (journal: Journal, applied: readonly string[]): JournalEntry[] => {
	const seen = new Set(applied.map((name) => name.replace(/\.sql$/, '')));
	return journal.entries.filter((entry) => !seen.has(entry.tag)).sort((a, b) => a.idx - b.idx);
};

const ADJECTIVES = [
	'brave', 'calm', 'clever', 'curious', 'eager', 'gentle', 'jolly', 'lively',
	'lucky', 'mellow', 'nimble', 'plucky', 'quiet', 'silent', 'spry', 'sunny',
];

const NOUNS = [
	'anchor', 'atlas', 'beacon', 'canyon', 'comet', 'delta', 'ember', 'harbor',
	'lagoon', 'meadow', 'moon', 'orbit', 'pebble', 'summit', 'thicket', 'willow',
];

/**
 * A stable, readable name derived from the index — deterministic, so
 * regenerating the same migration produces the same file name.
 */
export const migrationName = (index: number): string =>
	`${ADJECTIVES[index % ADJECTIVES.length]!}_${NOUNS[(index * 7) % NOUNS.length]!}`;
